[2023-10-22 08:10:37,715] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.wait_for_new_records scheduled__2023-10-22T07:50:00+00:00 [queued]>
[2023-10-22 08:10:37,727] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: exchange_rate_to_postgres.wait_for_new_records scheduled__2023-10-22T07:50:00+00:00 [queued]>
[2023-10-22 08:10:37,728] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 08:10:37,728] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2023-10-22 08:10:37,729] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-22 08:10:37,751] {taskinstance.py:1397} INFO - Executing <Task(SqlSensor): wait_for_new_records> on 2023-10-22 07:50:00+00:00
[2023-10-22 08:10:37,763] {standard_task_runner.py:52} INFO - Started process 1055 to run task
[2023-10-22 08:10:37,768] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_to_postgres', 'wait_for_new_records', 'scheduled__2023-10-22T07:50:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/get_exchange_rate.py', '--cfg-path', '/tmp/tmpqh7k5tcq', '--error-file', '/tmp/tmpb474aa8e']
[2023-10-22 08:10:37,774] {standard_task_runner.py:80} INFO - Job 19: Subtask wait_for_new_records
[2023-10-22 08:10:37,920] {task_command.py:371} INFO - Running <TaskInstance: exchange_rate_to_postgres.wait_for_new_records scheduled__2023-10-22T07:50:00+00:00 [running]> on host 1e02f9893e6c
[2023-10-22 08:10:38,104] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=andrey
AIRFLOW_CTX_DAG_ID=exchange_rate_to_postgres
AIRFLOW_CTX_TASK_ID=wait_for_new_records
AIRFLOW_CTX_EXECUTION_DATE=2023-10-22T07:50:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-22T07:50:00+00:00
[2023-10-22 08:10:38,131] {base.py:68} INFO - Using connection ID 'conn_exchange_rate' for task execution.
[2023-10-22 08:10:38,254] {sql.py:92} INFO - Poking: SELECT COUNT(*) FROM history_rate_btc_rub WHERE date_rate > 'None' (with parameters None)
[2023-10-22 08:10:38,284] {base.py:68} INFO - Using connection ID 'conn_exchange_rate' for task execution.
[2023-10-22 08:10:38,304] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/sql.py", line 93, in poke
    records = hook.get_records(self.sql, self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 162, in get_records
    cur.execute(sql)
psycopg2.errors.UndefinedTable: relation "history_rate_btc_rub" does not exist
LINE 1: SELECT COUNT(*) FROM history_rate_btc_rub WHERE date_rate > ...
                             ^

[2023-10-22 08:10:38,325] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=exchange_rate_to_***, task_id=wait_for_new_records, execution_date=20231022T075000, start_date=20231022T081037, end_date=20231022T081038
[2023-10-22 08:10:38,362] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task wait_for_new_records (relation "history_rate_btc_rub" does not exist
LINE 1: SELECT COUNT(*) FROM history_rate_btc_rub WHERE date_rate > ...
                             ^
; 1055)
[2023-10-22 08:10:38,399] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-22 08:10:38,480] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
